A = int(input())
B = int(input())
C = int(input())
N = A*B*C
S = str(N)
print(S.count('0'))
print(S.count('1'))
print(S.count('2'))
print(S.count('3'))
print(S.count('4'))
print(S.count('5'))
print(S.count('6'))
print(S.count('7'))
print(S.count('8'))
print(S.count('9'))
